table customers
	lineageTag: def220fb-fe2b-4966-9264-258e9d3dd928

	measure 'Total Customers' = DISTINCTCOUNT(customers[customer_unique_id])
		formatString: 0
		lineageTag: b737e32e-e3ad-4192-bba5-36fa045e956e

	measure 'Average Revenue per Customer' = DIVIDE([Total Sales], [Total Customers])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 7fcc7ec2-42ca-434f-b669-a736045b285a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Repeat Customer Rate' =
			
			VAR CustomerOrderCounts =
			    ADDCOLUMNS(
			        VALUES(customers[customer_unique_id]),
			        "OrderCount", CALCULATE(DISTINCTCOUNT(orders[order_id]))
			    )
			VAR RepeatCustomers =
			    COUNTROWS(
			        FILTER(CustomerOrderCounts, [OrderCount] > 1)
			    )
			RETURN
			    DIVIDE(RepeatCustomers, [Total Customers])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 772833b9-fa51-4c50-93dc-29facad58444

	measure 'Heatmap Value' = ""
		lineageTag: 8a2dba6f-0b8f-4a70-a7c9-c6d06bcd7a5b

	column customer_id
		dataType: string
		lineageTag: 57920e3a-de06-4f94-8e79-1a06b98fd63c
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: 3ae6ba1d-37e4-4054-ad23-373c105fe0ed
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 17248564-ce39-48d2-bb4b-838e11e884f5
		summarizeBy: none
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 262c8dc1-e366-4775-ab4f-0b972b900d65
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 5f5e4116-1ae5-41a8-9972-9ff4ea589d8a
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	partition customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\itsme\Desktop\Resources\Project 3\data\customers.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_unique_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

