table order_items
	lineageTag: 4448e38d-03dd-4dbb-aadd-9d42c18f01b2

	measure 'Total Sales' = SUM(order_items[price])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 9a538a05-a1cd-4241-86f8-b24ac2a15720

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Freight' = SUM(order_items[freight_value])
		lineageTag: d8d55084-c869-4b3c-9ab2-413de7b687d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Freight Cost % of Sales' = DIVIDE(SUM(order_items[freight_value]), [Total Sales], 0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b2a3b85c-8cad-4ff5-9443-2fb5728d9198

	measure 'Total Items Sold' =
			
			COUNTROWS(order_items)
		formatString: 0
		lineageTag: b7d8ffca-85fb-47bf-bfac-c99b712bdae2

	measure 'Average Item Price' =
			
			AVERAGE(order_items[price])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: bf4af6b0-67f2-4341-a851-8f2cf71c71b5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Average Items per Order' =
			
			DIVIDE(
			    [Total Items Sold],
			    [Total Orders]
			)
		formatString: 0
		lineageTag: 9833f5f1-2226-4afe-a8ed-6b275f047615

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Average Freight Cost' =
			
			AVERAGE(order_items[freight_value])
		lineageTag: 87d222f4-f35c-4c5d-8d9e-a2d54a315faa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Share of Sales' =
			
			DIVIDE(
			    SUM(order_items[price]),
			    CALCULATE(SUM(order_items[price]), ALL(products[product_category_name])
			))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 3cace11b-5ba4-4911-b2d9-aa829600616c

	column order_id
		dataType: string
		lineageTag: 1341ed03-0c7b-44a3-bb4b-f148a1f5d95a
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_item_id
		dataType: int64
		formatString: 0
		lineageTag: da9ac039-745c-4ec7-8a3a-21947aa0fc90
		summarizeBy: sum
		sourceColumn: order_item_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: e72a7819-aecb-4d4c-b417-8c011b4985da
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: string
		lineageTag: e4da026f-f51b-4403-9163-74ffdd048f7a
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column shipping_limit_date
		dataType: dateTime
		formatString: General Date
		lineageTag: dd784412-4799-4f35-a574-cb9dc960979e
		summarizeBy: none
		sourceColumn: shipping_limit_date

		variation Variation
			isDefault
			relationship: 94f48e9a-ffca-42b8-bf9b-c90babd2dee1
			defaultHierarchy: LocalDateTable_dd591123-5522-4037-82cd-0636a6d16f22.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		lineageTag: 08161842-c872-491b-b99a-d83ded724849
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column freight_value
		dataType: double
		lineageTag: bdd9ab94-b434-489b-8517-d25e15ace169
		summarizeBy: sum
		sourceColumn: freight_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition order_items = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\itsme\Desktop\Resources\Project 3\data\order_items.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"order_item_id", Int64.Type}, {"product_id", type text}, {"seller_id", type text}, {"shipping_limit_date", type datetime}, {"price", type number}, {"freight_value", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

