table order_payments
	lineageTag: 349cb918-01dd-4c88-9473-0299c20d1a5f

	measure 'Total Payment Value' = SUM(order_payments[payment_value])
		lineageTag: f25b1642-3312-4ab8-9fe6-c7b2ce6a0070

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Payment Value' = AVERAGE(order_payments[payment_value])
		lineageTag: 665d94de-b15e-4a46-928a-9c01d65d0cfd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order_id
		dataType: string
		lineageTag: 75875032-339d-42c8-9dea-8c7636dbc6ef
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_sequential
		dataType: int64
		formatString: 0
		lineageTag: 8aa03dc4-693e-4de4-ac2f-c815e4246696
		summarizeBy: sum
		sourceColumn: payment_sequential

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: 9e6dae53-d303-402a-b657-78bd0f659720
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_installments
		dataType: int64
		formatString: 0
		lineageTag: 864aefe2-1521-43bf-9b2a-e4d2c2eb1e88
		summarizeBy: sum
		sourceColumn: payment_installments

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: double
		lineageTag: 0b3175f3-248c-42fa-a15e-5599cf09d761
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition order_payments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\itsme\Desktop\Resources\Project 3\data\order_payments.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"payment_sequential", Int64.Type}, {"payment_type", type text}, {"payment_installments", Int64.Type}, {"payment_value", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

