table order_reviews
	lineageTag: ca5949d6-033c-49e4-bbb0-aea1a7205275

	measure 'Average Review Score' = AVERAGE(order_reviews[review_score])
		lineageTag: afba9697-263d-49a1-9176-10b84db83e70

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column review_id
		dataType: string
		lineageTag: 440befed-4ffb-4843-9fc7-19d6b8fb34e2
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 9ef7f44b-f637-41aa-86fc-d0065b3345f7
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: 13494aa6-2689-48ac-befd-478d0b4babc2
		summarizeBy: sum
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column review_creation_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e1b086d7-cacb-456f-b20b-621cd80582bb
		summarizeBy: none
		sourceColumn: review_creation_date

		variation Variation
			isDefault
			relationship: 28a90e5c-f063-40ac-b0cc-bf51eb87d5b3
			defaultHierarchy: LocalDateTable_07cdbe49-da24-425f-bcb5-e2d7da70c9a7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column review_answer_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 1c33fa81-ff8d-4643-9b37-d20b59b0d2aa
		summarizeBy: none
		sourceColumn: review_answer_timestamp

		variation Variation
			isDefault
			relationship: 176fd79e-2798-49bd-b975-fc40b2d9cedc
			defaultHierarchy: LocalDateTable_d163d939-bb61-4f84-9432-975c90a68290.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition order_reviews = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\itsme\Desktop\Resources\Project 3\data\order_reviews.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}}),
				    #"Removed review comment columns" = Table.RemoveColumns(#"Changed Type",{"review_comment_title", "review_comment_message"})
				in
				    #"Removed review comment columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

