table orders
	lineageTag: fa572b53-32b1-40a2-8e03-8a94afc9b02e

	column order_id
		dataType: string
		lineageTag: e6dfdcf7-8877-4757-8818-5794250ea8cc
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: f32b45b5-0070-41cf-8b3a-fc627e03bcd9
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: 1405329e-75c4-473f-87e6-7f7d7bab2375
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column order_purchase_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 08cb200d-b0a0-4258-bdd5-c99e3bafa8c5
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

		variation Variation
			isDefault
			relationship: 0eee0a0b-4ccf-443b-9e67-2e6c138b3045
			defaultHierarchy: LocalDateTable_973bf1e5-933e-498d-9f75-2f76ee85709d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_approved_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 8268ff60-82e1-424a-bc27-a7d24651d35f
		summarizeBy: none
		sourceColumn: order_approved_at

		variation Variation
			isDefault
			relationship: eeff894c-4f3d-471a-98b3-fe755c36271d
			defaultHierarchy: LocalDateTable_16953d7a-179a-4832-a1d9-eef992ec6c7b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 64ab44e1-640d-4aeb-978c-edfbcbcf81af
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

		variation Variation
			isDefault
			relationship: 4d63f23a-f7e7-4faf-ad10-9535f49e0154
			defaultHierarchy: LocalDateTable_a774c5a6-d61d-494d-82cc-10a4f6241b5d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_delivered_customer_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9bb71a08-0507-400d-af46-4b675b5c4039
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		variation Variation
			isDefault
			relationship: 903f2f90-2cf6-4993-88e2-a6a2bd7e5a4e
			defaultHierarchy: LocalDateTable_137ec8a2-7ea0-4cd1-8557-aeda4f547c0f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 6b4801ec-2a17-4fa0-b18a-23cfdc2e7941
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		variation Variation
			isDefault
			relationship: c70e501b-6317-48d2-81e6-71184ee85ed9
			defaultHierarchy: LocalDateTable_2c3b6cd1-950a-4e08-b030-eb5e077cfdb9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\itsme\Desktop\Resources\Project 3\data\orders.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"customer_id", type text}, {"order_status", type text}, {"order_purchase_timestamp", type datetime}, {"order_approved_at", type datetime}, {"order_delivered_carrier_date", type datetime}, {"order_delivered_customer_date", type datetime}, {"order_estimated_delivery_date", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

