table products
	lineageTag: 0fc7e367-073a-4879-9ca7-4b0684c95429

	column product_id
		dataType: string
		lineageTag: a8fa9270-60d0-4406-9455-4edf0c48c189
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_category_name
		dataType: string
		lineageTag: 9480cbcf-0441-4317-85c0-d4bc0205083e
		summarizeBy: none
		sourceColumn: product_category_name

		annotation SummarizationSetBy = Automatic

	column product_name_lenght
		dataType: int64
		formatString: 0
		lineageTag: c4cd1324-4b0b-4d40-a7e1-92ea06eca7d7
		summarizeBy: sum
		sourceColumn: product_name_lenght

		annotation SummarizationSetBy = Automatic

	column product_description_lenght
		dataType: int64
		formatString: 0
		lineageTag: b5454b9e-4b73-4a95-83a4-ab4ebff985f6
		summarizeBy: sum
		sourceColumn: product_description_lenght

		annotation SummarizationSetBy = Automatic

	column product_photos_qty
		dataType: int64
		formatString: 0
		lineageTag: 1ef5af3e-7716-438f-9245-94c1730896cf
		summarizeBy: sum
		sourceColumn: product_photos_qty

		annotation SummarizationSetBy = Automatic

	column product_weight_g
		dataType: int64
		formatString: 0
		lineageTag: 4a48db6e-8738-4074-a112-4cbbfb7ff39d
		summarizeBy: sum
		sourceColumn: product_weight_g

		annotation SummarizationSetBy = Automatic

	column product_length_cm
		dataType: int64
		formatString: 0
		lineageTag: 46eb4615-f36d-4d51-9490-689107b6c69b
		summarizeBy: sum
		sourceColumn: product_length_cm

		annotation SummarizationSetBy = Automatic

	column product_height_cm
		dataType: int64
		formatString: 0
		lineageTag: 060a4e48-99b4-4f8f-a119-88feea9468ec
		summarizeBy: sum
		sourceColumn: product_height_cm

		annotation SummarizationSetBy = Automatic

	column product_width_cm
		dataType: int64
		formatString: 0
		lineageTag: cb0fbafb-8b70-419e-b045-7876bc93f881
		summarizeBy: sum
		sourceColumn: product_width_cm

		annotation SummarizationSetBy = Automatic

	column 'product_category_name.1.product_category_name_english'
		dataType: string
		lineageTag: 9c8256ab-d67b-4f2f-a859-71c345819da0
		summarizeBy: none
		sourceColumn: product_category_name.1.product_category_name_english

		annotation SummarizationSetBy = Automatic

	column product_category_name_english_final
		dataType: string
		lineageTag: 6f2ff1df-249d-4e85-8a65-0e55dc6a2c61
		summarizeBy: none
		sourceColumn: product_category_name_english_final

		annotation SummarizationSetBy = Automatic

	partition products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\itsme\Desktop\Resources\Project 3\data\products.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", type text}, {"product_category_name", type text}, {"product_name_lenght", Int64.Type}, {"product_description_lenght", Int64.Type}, {"product_photos_qty", Int64.Type}, {"product_weight_g", Int64.Type}, {"product_length_cm", Int64.Type}, {"product_height_cm", Int64.Type}, {"product_width_cm", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"product_category_name"}, product_category_name, {"product_category_name"}, "product_category_name.1", JoinKind.LeftOuter),
				    #"Expanded product_category_name.1" = Table.ExpandTableColumn(#"Merged Queries", "product_category_name.1", {"product_category_name_english"}, {"product_category_name.1.product_category_name_english"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded product_category_name.1", "product_category_name_english_final", each if [product_category_name.1.product_category_name_english] <> null then [product_category_name.1.product_category_name_english] else if [product_category_name] = "pc_gamer" then "pc_gamer" else if [product_category_name] = "portateis_cozinha_e_preparadores_de_alimentos" then "portable_kitchen_and_food_preparers" else "Uncategorized")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

